"""Public API for the marmoset convergence reproducibility pipeline."""

__version__ = "0.2.0"

from .calls import (
    AudioPreflight,
    call_basename,
    clean_call_path,
    deduplicate_calls,
    preflight_audio,
)
from .dtw import (
    DEFAULT_DTW,
    DTWConfig,
    DTWResult,
    exact_dtw,
    exact_dtw_distance,
    pairwise_exact_dtw_condensed,
)
from .exceptions import (
    AudioPreflightError,
    CacheValidationError,
    DataValidationError,
    DuplicateCallConflictError,
    ExpensiveComputationDisabled,
    MarmosetConvergenceError,
)
from .identifiers import (
    SessionKey,
    canonical_comparison_id,
    canonical_pair_id,
    canonical_session_id,
)
from .matrices import (
    CondensedDistanceMatrix,
    DistanceBundle,
    FeatureDistanceMatrix,
    SequenceRepresentationCache,
    condensed_index,
    condensed_to_square,
    feature_distance_condensed,
    load_dtw_distance_cache,
    load_sequence_distance_cache,
    load_sequence_representation_cache,
    square_to_condensed,
)
from .model_tables import (
    CALL_METRICS,
    SEQUENCE_METRICS,
    aggregate_item_distances,
    attach_repertoire_distances,
    build_model_table,
    joint_zscore_within_metric,
)
from .paths import ProjectPaths
from .provenance import (
    DTW_PARAMETERS,
    EMBEDDING_PARAMETERS,
    LOCAL_ALIGNMENT_PARAMETERS,
    MODEL_TABLE_PARAMETERS,
    SEQUENCE_REPRESENTATION_PARAMETERS,
    VAE_PARAMETERS,
    ArtifactRecord,
    CacheManifest,
    load_and_validate_manifest,
    ordered_ids_sha256,
    sha256_file,
)
from .sequence import (
    DEFAULT_SMITH_WATERMAN,
    LocalAlignmentDistances,
    SequenceRepresentations,
    SmithWatermanConfig,
    bigram_distance,
    bigram_frequency_vector,
    build_sequence_representations,
    local_alignment_distance_matrix,
    normalized_local_alignment_similarity,
    phee_repeat_distance,
    phee_repeat_vector,
    repertoire_local_alignment_similarity,
    similarities_to_distances,
    smith_waterman_score,
    transition_probability_distance,
    transition_probability_vector,
)
from .sessions import (
    add_repertoire_ids,
    build_session_inventory,
    build_session_pairs,
    normalize_context,
)

__all__ = [
    "__version__",
    "AudioPreflight",
    "AudioPreflightError",
    "ArtifactRecord",
    "CALL_METRICS",
    "CacheManifest",
    "CacheValidationError",
    "CondensedDistanceMatrix",
    "DEFAULT_DTW",
    "DEFAULT_SMITH_WATERMAN",
    "DTWConfig",
    "DTWResult",
    "DTW_PARAMETERS",
    "EMBEDDING_PARAMETERS",
    "DataValidationError",
    "DistanceBundle",
    "DuplicateCallConflictError",
    "ExpensiveComputationDisabled",
    "FeatureDistanceMatrix",
    "LOCAL_ALIGNMENT_PARAMETERS",
    "LocalAlignmentDistances",
    "MODEL_TABLE_PARAMETERS",
    "MarmosetConvergenceError",
    "ProjectPaths",
    "SEQUENCE_METRICS",
    "SEQUENCE_REPRESENTATION_PARAMETERS",
    "SequenceRepresentationCache",
    "SequenceRepresentations",
    "SessionKey",
    "SmithWatermanConfig",
    "VAE_PARAMETERS",
    "add_repertoire_ids",
    "aggregate_item_distances",
    "attach_repertoire_distances",
    "bigram_distance",
    "bigram_frequency_vector",
    "build_model_table",
    "build_sequence_representations",
    "build_session_inventory",
    "build_session_pairs",
    "call_basename",
    "canonical_comparison_id",
    "canonical_pair_id",
    "canonical_session_id",
    "clean_call_path",
    "condensed_index",
    "condensed_to_square",
    "deduplicate_calls",
    "exact_dtw",
    "exact_dtw_distance",
    "feature_distance_condensed",
    "joint_zscore_within_metric",
    "load_and_validate_manifest",
    "load_dtw_distance_cache",
    "load_sequence_distance_cache",
    "load_sequence_representation_cache",
    "local_alignment_distance_matrix",
    "normalize_context",
    "normalized_local_alignment_similarity",
    "ordered_ids_sha256",
    "pairwise_exact_dtw_condensed",
    "phee_repeat_distance",
    "phee_repeat_vector",
    "preflight_audio",
    "repertoire_local_alignment_similarity",
    "sha256_file",
    "similarities_to_distances",
    "smith_waterman_score",
    "square_to_condensed",
    "transition_probability_distance",
    "transition_probability_vector",
]
